package com.FraudBusters.TransactionMonitoring.Controllers;

import com.FraudBusters.TransactionMonitoring.controllers.AlertOpsController;
import com.FraudBusters.TransactionMonitoring.exceptions.GlobalApiExceptionHandler;
import com.FraudBusters.TransactionMonitoring.models.AlertEntity;
import com.FraudBusters.TransactionMonitoring.models.enums.AlertStatus;
import com.FraudBusters.TransactionMonitoring.models.enums.SeverityLevel;
import com.FraudBusters.TransactionMonitoring.services.AlertOpsService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;

import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Unit tests for {@link AlertOpsController}.
 *
 * Uses @WebMvcTest to load only the web layer.
 * AlertOpsService is mocked via @MockitoBean.
 * All tests follow Given / When / Then format.
 */
@WebMvcTest(AlertOpsController.class)
@Import(GlobalApiExceptionHandler.class)
class AlertOpsControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private AlertOpsService alertOpsService;

    private AlertEntity buildAlert(Long id, String alertCode, SeverityLevel severity, AlertStatus status) {
        return AlertEntity.builder()
                .id(id)
                .alertCode(alertCode)
                .severity(severity)
                .status(status)
                .riskScore(new BigDecimal("88.50"))
                .title("Suspicious transaction")
                .description("Alert generated by rule engine")
                .createdAt(LocalDateTime.of(2026, 8, 6, 10, 0))
                .build();
    }

    // -------------------------------------------------------------------------
    // GET /api/alerts/all
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("GET /api/alerts/all - returns all alerts with HTTP 200")
    void getAllAlerts_success_returnsList() throws Exception {

        // Given
        AlertEntity first = buildAlert(1L, "ALT-ALL-001", SeverityLevel.HIGH, AlertStatus.OPEN);
        AlertEntity second = buildAlert(2L, "ALT-ALL-002", SeverityLevel.MEDIUM, AlertStatus.CLOSED);

        when(alertOpsService.getAllAlerts()).thenReturn(List.of(first, second));

        // When
        mockMvc.perform(get("/api/alerts/all"))

                // Then
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$", hasSize(2)))
                .andExpect(jsonPath("$[0].id", is(1)))
                .andExpect(jsonPath("$[0].alertCode", is("ALT-ALL-001")))
                .andExpect(jsonPath("$[0].severity", is("HIGH")))
                .andExpect(jsonPath("$[0].status", is("OPEN")))
                .andExpect(jsonPath("$[1].id", is(2)))
                .andExpect(jsonPath("$[1].alertCode", is("ALT-ALL-002")))
                .andExpect(jsonPath("$[1].status", is("CLOSED")));

        verify(alertOpsService, times(1)).getAllAlerts();
    }

    @Test
    @DisplayName("GET /api/alerts/all - returns empty JSON array when no alerts exist")
    void getAllAlerts_emptyList_returnsEmptyArray() throws Exception {

        // Given
        when(alertOpsService.getAllAlerts()).thenReturn(Collections.emptyList());

        // When
        mockMvc.perform(get("/api/alerts/all"))

                // Then
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$", hasSize(0)))
                .andExpect(content().json("[]"));

        verify(alertOpsService, times(1)).getAllAlerts();
    }

    @Test
    @DisplayName("GET /api/alerts/all - returns 500 on unexpected service exception")
    void getAllAlerts_serviceThrowsUnexpectedException_returns500() throws Exception {

        // Given
        when(alertOpsService.getAllAlerts()).thenThrow(new RuntimeException("Unexpected DB exception"));

        // When
        mockMvc.perform(get("/api/alerts/all"))

                // Then
                .andExpect(status().isInternalServerError())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.status", is(500)))
                .andExpect(jsonPath("$.error", is("Internal Server Error")))
                .andExpect(jsonPath("$.message", is("Unexpected server error.")))
                .andExpect(jsonPath("$.path", is("/api/alerts/all")));

        verify(alertOpsService, times(1)).getAllAlerts();
    }

    // -------------------------------------------------------------------------
    // GET /api/alerts/active
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("GET /api/alerts/active - returns active alerts with HTTP 200")
    void getActiveAlerts_success_returnsList() throws Exception {

        // Given
        AlertEntity first = buildAlert(3L, "ALT-ACT-001", SeverityLevel.CRITICAL, AlertStatus.OPEN);
        AlertEntity second = buildAlert(4L, "ALT-ACT-002", SeverityLevel.HIGH, AlertStatus.ACKNOWLEDGED);

        when(alertOpsService.getActiveAlerts()).thenReturn(List.of(first, second));

        // When
        mockMvc.perform(get("/api/alerts/active"))

                // Then
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$", hasSize(2)))
                .andExpect(jsonPath("$[0].alertCode", is("ALT-ACT-001")))
                .andExpect(jsonPath("$[0].severity", is("CRITICAL")))
                .andExpect(jsonPath("$[0].status", is("OPEN")))
                .andExpect(jsonPath("$[1].alertCode", is("ALT-ACT-002")))
                .andExpect(jsonPath("$[1].status", is("ACKNOWLEDGED")));

        verify(alertOpsService, times(1)).getActiveAlerts();
    }

    @Test
    @DisplayName("GET /api/alerts/active - returns empty JSON array when no active alerts exist")
    void getActiveAlerts_emptyList_returnsEmptyArray() throws Exception {

        // Given
        when(alertOpsService.getActiveAlerts()).thenReturn(Collections.emptyList());

        // When
        mockMvc.perform(get("/api/alerts/active"))

                // Then
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$", hasSize(0)))
                .andExpect(content().json("[]"));

        verify(alertOpsService, times(1)).getActiveAlerts();
    }

    @Test
    @DisplayName("GET /api/alerts/active - returns 500 on unexpected service exception")
    void getActiveAlerts_serviceThrowsUnexpectedException_returns500() throws Exception {

        // Given
        when(alertOpsService.getActiveAlerts()).thenThrow(new RuntimeException("Unexpected mapper failure"));

        // When
        mockMvc.perform(get("/api/alerts/active"))

                // Then
                .andExpect(status().isInternalServerError())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.status", is(500)))
                .andExpect(jsonPath("$.error", is("Internal Server Error")))
                .andExpect(jsonPath("$.message", is("Unexpected server error.")))
                .andExpect(jsonPath("$.path", is("/api/alerts/active")));

        verify(alertOpsService, times(1)).getActiveAlerts();
    }
}

